### ISSUE TITLE
同意楼上，不知道怎么运行

### ISSUE THREAD

**Issue by oyai32** [tower1229/WidgetsPlayground#3]
本人近期才接触vue，用的是seajs+vue+axios+es6，看到博主的文章进来的，但是不知道怎么运行，我现在的 项目还不是前后端分离的。
另，看源码发现
1、box的引用识别不到，整个工程也没有box.js相关的文件
2、有几个地方用了jq的事件委托，不会有影响吗，为什么不用vue的click
3、vue相关js的引用为什么不放到seajs的config里，特意这样的？因为我是放里面了
4、每个模板都单独写了个文件夹，模板的html都写在了temp.htm，但是我不知道怎么调用到这个htm的
。。。。发现自己不知道的东西太多了，求大神解答

**Comment by tower1229** [comment]
这个项目的目的是为了演示如何不依赖构建工具实现模块化开发，所以部分UI插件直接借用了我的另一个项目Flow-UI实现，Flow-UI是一个jQuery技术栈的UI框架，而且用的是远程插件库，所以box文件不在项目里；vue作为底层框架我觉得更适合在页面中同步加载，seajs模块主要负责UI部分可以异步加载；模板的拆分和异步加载利用了vue的异步模块特性实现，传输过程其实就是ajax。

这个项目的文档我会尽快补充上来。

**Comment by tower1229** [comment]
https://github.com/tower1229/WidgetsPlayground/commit/2608a69c4895be728fc35c17dbbe727d3c522615
