### ISSUE TITLE
vue单文件支持

### ISSUE THREAD

**Issue by mydaoyuan** [tower1229/WidgetsPlayground#4]
[http-vue-loader](https://github.com/FranckFreiburger/http-vue-loader)
还可以在客户端进行vue编译，使用起来体验更好。😃

**Comment by tower1229** [comment]
确实可以用http-vue-loader替换掉seajs，再用axios替换掉jQuery.ajax，基本上可以做到跟cli环境的开发体验一致（除了开发环境实时预览）。

**Comment by UmbraCi** [comment]
> 确实可以用http-vue-loader替换掉seajs，再用axios替换掉jQuery.ajax，基本上可以做到跟cli环境的开发体验一致（除了开发环境实时预览）。

你好，我今天尝试了下用http-vue-loader写单个VUE文件，但是原有项目是seajs二次封装的，直接写VUE单文件确实舒服，但是不知道如何引入外部define函数内seajs的module.export导出的js对象以及HTTP请求对象，其实用博主的方法确实很好，但是博主的html写在JS的字符串模板里面看起来还是觉得有点怪怪的，另外也无法使用LESS和scoped，希望博主有空的时候能指点一下

**Comment by tower1229** [comment]
> > 确实可以用http-vue-loader替换掉seajs，再用axios替换掉jQuery.ajax，基本上可以做到跟cli环境的开发体验一致（除了开发环境实时预览）。
> 
> 你好，我今天尝试了下用http-vue-loader写单个VUE文件，但是原有项目是seajs二次封装的，直接写VUE单文件确实舒服，但是不知道如何引入外部define函数内seajs的module.export导出的js对象以及HTTP请求对象，其实用博主的方法确实很好，但是博主的html写在JS的字符串模板里面看起来还是觉得有点怪怪的，另外也无法使用LESS和scoped，希望博主有空的时候能指点一下

这个项目是jQuery时代对前端组件管理的一种尝试，今天的Vue组件化能力已经完爆这个项目了，单文件组件、组件props动态传参实现自定义样式都很容易实现，所以请放过这个项目吧^^

**Comment by UmbraCi** [comment]
> > > 确实可以用http-vue-loader替换掉seajs，再用axios替换掉jQuery.ajax，基本上可以做到跟cli环境的开发体验一致（除了开发环境实时预览）。
> > 
> > 
> > 你好，我今天尝试了下用http-vue-loader写单个VUE文件，但是原有项目是seajs二次封装的，直接写VUE单文件确实舒服，但是不知道如何引入外部define函数内seajs的module.export导出的js对象以及HTTP请求对象，其实用博主的方法确实很好，但是博主的html写在JS的字符串模板里面看起来还是觉得有点怪怪的，另外也无法使用LESS和scoped，希望博主有空的时候能指点一下
> 
> 这个项目是jQuery时代对前端组件管理的一种尝试，今天的Vue组件化能力已经完爆这个项目了，单文件组件、组件props动态传参实现自定义样式都很容易实现，所以请放过这个项目吧^^

答主的意思是，让我不要在seajs这个老项目上渐进升级VUE嘛，因为公司不让重构，目前还是在用渐进的方式

**Comment by tower1229** [comment]
> > > > 确实可以用http-vue-loader替换掉seajs，再用axios替换掉jQuery.ajax，基本上可以做到跟cli环境的开发体验一致（除了开发环境实时预览）。
> > > 
> > > 
> > > 你好，我今天尝试了下用http-vue-loader写单个VUE文件，但是原有项目是seajs二次封装的，直接写VUE单文件确实舒服，但是不知道如何引入外部define函数内seajs的module.export导出的js对象以及HTTP请求对象，其实用博主的方法确实很好，但是博主的html写在JS的字符串模板里面看起来还是觉得有点怪怪的，另外也无法使用LESS和scoped，希望博主有空的时候能指点一下
> > 
> > 
> > 这个项目是jQuery时代对前端组件管理的一种尝试，今天的Vue组件化能力已经完爆这个项目了，单文件组件、组件props动态传参实现自定义样式都很容易实现，所以请放过这个项目吧^^
> 
> 答主的意思是，让我不要在seajs这个老项目上渐进升级VUE嘛，因为公司不让重构，目前还是在用渐进的方式

这个项目本身只是个管理组件的工具，目前组件的实现方式是基于seajs+jquery的纯前端代码，如果你希望换成vue单文件组件的话，整个项目需要基于vue-cli重构，因为现在是引入运行时编译的vue库，不支持真正的vue单文件组件。然后主要修改的是`src/components/play-time.js`这个文件，这里实现了组件的渲染逻辑，基于vue的组件系统这里的逻辑可以极大简化。
